# Generated by Django 4.2.1 on 2023-06-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='option',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question_survey', to='trial_app.user'),
        ),
        migrations.AddField(
            model_name='survey',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_survey', to='trial_app.user'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SurveyResult',
        ),
    ]
