# Generated by Django 4.2.1 on 2023-06-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
