# Generated by Django 4.2.1 on 2023-06-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0003_surveycount_surveymark_delete_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
