# Generated by Django 4.2.1 on 2023-06-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0004_delete_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveymark',
            old_name='user',
            new_name='username',
        ),
    ]
